use_frameworks!

target 'MAGComfortTextInput_Example' do
  pod 'MAGComfortTextInput', :path => '../'

  target 'MAGComfortTextInput_Tests' do
    inherit! :search_paths

    
  end

    pod 'MAGMatveevReusable', :git => 'https://github.com/Magora-IOS/MAGMatveevReusable.git'
    pod 'libextobjc', '~> 0.4.1'
#    pod 'MAGMatveevReusable'

end
